export let rondaextra1 = [
    {
        preguntaTexto: "Esta ley establece que: La fuerza entre dos cargas es proporcional al producto de las cargas e inversamente proporcional al cuadrado de la distancia que los separa",
        preguntaImagen: "",
        opciones: {
            opcion1: "ley de Ohm",
            opcion2: "ley de Gauss",
            opcion3: "ley de Kirchoff",
            opcion4: "ley de Coulomb",
        },
        respuesta: 4,
        categoria: "Ingeniería Ambiental",
        dificultad: "Media",
    },
    {
        preguntaTexto: "Se define como la ruptura de un enlace quimico debido a la absorcion de un foton en la molecula",
        preguntaImagen: "",
        opciones: {
            opcion1: "radiacion",
            opcion2: "fotodisociacion",
            opcion3: "isomerización",
            opcion4: "ionización",
        },
        respuesta: 2,
        categoria: "Ingeniería Ambiental",
        dificultad: "Media",
    },
    {
        preguntaTexto: "Accion que se llevan a cabo desde que se elabora el producto hasta que se entrega, garantizando la llegada del producto o bien.",
        preguntaImagen: "",
        opciones: {
            opcion1: "Abastecimiento",
            opcion2: "Distribución",
            opcion3: "Transporte",
            opcion4: "Producción",
        },
        respuesta: 2,
        categoria: "Ingeniería en Logística",
        dificultad: "Media",
    },
    {
        preguntaTexto: "¿Cuál de los siguientes números es divisible por 3 y por 5?",
        preguntaImagen: "",
        opciones: {
            opcion1: "685",
            opcion2: "745",
            opcion3: "880",
            opcion4: "975",
        },
        respuesta: 4,
        categoria: "Matemáticas",
        dificultad: "Media",
    },
    {
        preguntaTexto: "Se encuetra dentro de la célula eucariota vegetal en la cual se retiene o almacena agua",
        preguntaImagen: "",
        opciones: {
            opcion1: "retículo endoplásmico",
            opcion2: "pared celular",
            opcion3: "citoplasma",
            opcion4: "vacuola",
        },
        respuesta: 4,
        categoria: "Ingeniería Ambiental",
        dificultad: "Fácil",
    },
    {
        preguntaTexto: "Es el número de lineas de campo electrico que atraviesan una superficie",
        preguntaImagen: "",
        opciones: {
            opcion1: "vector unitario",
            opcion2: "flujo electrico",
            opcion3: "fuerza electrostática",
            opcion4: "carga electrica neta",
        },
        respuesta: 2,
        categoria: "Ingeniería Ambiental",
        dificultad: "Difícil",
    },
    {
        preguntaTexto: "Magnitud escalar, en la cual el trabajo por unidad de carga positiva que se realizan fuerzas electricas al mover una carga de prueba desde un punto A a un punto B",
        preguntaImagen: "",
        opciones: {
            opcion1: "Trabajo",
            opcion2: "diferencia de potencial",
            opcion3: "fuerza electrica",
            opcion4: "intensidad de campo electrico",
        },
        respuesta: 2,
        categoria: "Ingeniería Ambiental",
        dificultad: "Fácil",
    },
    {
        preguntaTexto: "Cual de los siguientes terminos no pertenece a las cinco esferas ambietales",
        preguntaImagen: "",
        opciones: {
            opcion1: "atmosfera",
            opcion2: "homosfera",
            opcion3: "antroposfera",
            opcion4: "hidrosfera",
        },
        respuesta: 2,
        categoria: "Ingeniería Ambiental",
        dificultad: "Fácil",
    },
    {
        preguntaTexto: "Son redes que abarcan distancias entre países y continentes",
        preguntaImagen: "",
        opciones: {
            opcion1: "WAN",
            opcion2: "LAN",
            opcion3: "PAN",
            opcion4: "LAN",
        },
        respuesta: 1,
        categoria: "Ingeniería en Datos",
        dificultad: "Media",
    },
    {
        preguntaTexto: "¿De qué país es el futbolista Zlatan Ibrahimović?",
        preguntaImagen: "",
        opciones: {
            opcion1: "Suecia",
            opcion2: "Inglaterra",
            opcion3: "Estados Unidos",
            opcion4: "Francia",
        },
        respuesta: 1,
        categoria: "Cultura General",
        dificultad: "Fácil",
    },
    {
        preguntaTexto: "Por sus siglas en inglés, ¿qué significa SCM en logística?",
        preguntaImagen: "",
        opciones: {
            opcion1: "System Chain Management",
            opcion2: "Supply Chain Management",
            opcion3: "Supply Change Management",
            opcion4: "Supply Chain Measure",
        },
        respuesta: 2,
        categoria: "Ingeniería en Logística",
        dificultad: "Media",
    },
    {
        preguntaTexto: "Una compuerta AND realiza",
        preguntaImagen: "",
        opciones: {
            opcion1: "Suma lógica",
            opcion2: "Resta lógica",
            opcion3: "Producto lógico",
            opcion4: "Inversión lógica",
        },
        respuesta: 3,
        categoria: "Ingeniería en Datos",
        dificultad: "Media",
    },
    {
        preguntaTexto: "¿Qué representa un falso positivo en una matrz de confusión?",
        preguntaImagen: "",
        opciones: {
            opcion1: "El valor real es positivo y la prueba predijo tambien que era positivo",
            opcion2: "El valor real es negativo y la prueba predijo tambien que el resultado era negativo.",
            opcion3: "El valor real es negativo, y la prueba predijo que el resultado es positivo.",
            opcion4: "El valor real es positivo, y la prueba predijo que el resultado es negativo.",
        },
        respuesta: 3,
        categoria: "Ingeniería en Datos",
        dificultad: "Media",
    },
    {
        preguntaTexto: "¿Cuál es el otro nombre de la Vitamina C?",
        preguntaImagen: "",
        opciones: {
            opcion1: "Retinol",
            opcion2: "Ácido ascórbico",
            opcion3: "Tocoferol",
            opcion4: "Filoquinona",
        },
        respuesta: 2,
        categoria: "Ciencias básicas",
        dificultad: "Fácil",
    }
]