export let rondaprueba = [
    {
        preguntaTexto: "Todo cuerpo persevera en su estado de reposo o movimiento uniforme y rectilíneo a no ser que sea obligado a cambiar su estado por fuerzas impresas sobre él",
        preguntaImagen: "",
        tiempo: 15,
        opciones: {
            opcion1: "Segunda ley de Newton",
            opcion2: "Tercera de la Termodinamica",
            opcion3: "Tercera ley de Newton",
            opcion4: "Ley de la Inercia",
        },
        respuesta: 4,
        categoria: "Ciencias Básicas",
        dificultad: "Fácil",
    },
    {
        preguntaTexto: "Es el número total de protones que tiene el átomo",
        preguntaImagen: "",
        tiempo: 15,
        opciones: {
            opcion1: "Masa atomica",
            opcion2: "Número de masa",
            opcion3: "Número atómico",
            opcion4: "Masa Molecular",
        },
        respuesta: 3,
        categoria: "Ciencias Básicas",
        dificultad: "Fácil",
    },
    {
        preguntaTexto: "Convierte 300° C a Fahrenheit",
        preguntaImagen: "",
        tiempo: 15,
        opciones: {
            opcion1: "680°F",
            opcion2: "572°F",
            opcion3: "750°F",
            opcion4: "483°F",
        },
        respuesta: 2,
        categoria: "Ciencias Básicas",
        dificultad: "Difícil",
    },
    {
        preguntaTexto: "Son compuestos que poseen átomos de hidrógeno facilmente remplazables por átomos de metal",
        preguntaImagen: "",
        tiempo: 15,
        opciones: {
            opcion1: "Hidróxidos",
            opcion2: "Ácidos",
            opcion3: "Bases",
            opcion4: "Óxidos",
        },
        respuesta: 2,
        categoria: "Ciencias Básicas",
        dificultad: "Difícil",
    },
    {
        preguntaTexto: "La función cosecante es la función inversa del...",
        preguntaImagen: "",
        tiempo: 15,
        opciones: {
            opcion1: "Seno",
            opcion2: "Coseno",
            opcion3: "Cotangente",
            opcion4: "Tangente",
        },
        respuesta: 1,
        categoria: "Matemáticas",
        dificultad: "Fácil",
    },
    {
        preguntaTexto: "¿En que operación el resultado es el cociente?",
        preguntaImagen: "",
        tiempo: 15,
        opciones: {
            opcion1: "Multiplicación",
            opcion2: "Suma",
            opcion3: "Resta",
            opcion4: "División",
        },
        respuesta: 4,
        categoria: "Matemáticas",
        dificultad: "Fácil",
    },
    {
        preguntaTexto: "¿Cuantos números primos hay del 1 al 100?",
        preguntaImagen: "",
        tiempo: 15,
        opciones: {
            opcion1: "18",
            opcion2: "25",
            opcion3: "61",
            opcion4: "43",
        },
        respuesta: 2,
        categoria: "Matemáticas",
        dificultad: "Difícil",
    },
    {
        preguntaTexto: "Si 2x - 5 = 13, entonces 4x + 7 es igual a:",
        preguntaImagen: "",
        tiempo: 15,
        opciones: {
            opcion1: "39",
            opcion2: "34",
            opcion3: "43",
            opcion4: "47",
        },
        respuesta: 4,
        categoria: "Matemáticas",
        dificultad: "Difícil",
    },
    {
        preguntaTexto: "¿Cuántos tentáculos tiene un calamar?",
        preguntaImagen: "",
        tiempo: 15,
        opciones: {
            opcion1: "20",
            opcion2: "4",
            opcion3: "8",
            opcion4: "10",
        },
        respuesta: 3,
        categoria: "Ingenierias",
        dificultad: "Fácil",
    },
    {
        preguntaTexto: "¿Cuál es el idioma oficial de Brasil?",
        preguntaImagen: "",
        tiempo: 15,
        opciones: {
            opcion1: "Brasileño",
            opcion2: "Francés",
            opcion3: "Inglés",
            opcion4: "Portugués",
        },
        respuesta: 4,
        categoria: "Ingenierias",
        dificultad: "Fácil",
    },
    {
        preguntaTexto: "¿Quién era el dios romano de la guerra?",
        preguntaImagen: "",
        tiempo: 15,
        opciones: {
            opcion1: "Ares",
            opcion2: "Júpiter",
            opcion3: "Marte",
            opcion4: "Belerofonte",
        },
        respuesta: 3,
        categoria: "Ingenierias",
        dificultad: "Media",
    },
    {
        preguntaTexto: "¿Por qué es reconocido Serguéi Rajmáninov?",
        preguntaImagen: "",
        tiempo: 15,
        opciones: {
            opcion1: "Por sus contribuciones al mundo de la física cuántica",
            opcion2: "Por sus contribuciones al mundo de la música",
            opcion3: "Por sus contribuciones al mundo de la pintura",
            opcion4: "Por sus contribuciones al mundo de la literatura",
        },
        respuesta: 2,
        categoria: "Ingenierias",
        dificultad: "Media",
    },
    {
        preguntaTexto: "¿Cuáles de los siguientes Software son lenguajes de Programación?",
        preguntaImagen: "",
        tiempo: 15,
        opciones: {
            opcion1: "Word, Excel, Power Point",
            opcion2: "C#, Java, Visual Basic",
            opcion3: "Pseint, Raptor, Flowchart",
            opcion4: "Windows, Linux, Mac OS",
        },
        respuesta: 2,
        categoria: "Cultura General",
        dificultad: "Fácil",
    },
    {
        preguntaTexto: "Es la relación entre los niveles productivos logrados y los recursos utilizados durante la producción",
        preguntaImagen: "",
        tiempo: 15,
        opciones: {
            opcion1: "Competitividad",
            opcion2: "Costo Beneficio",
            opcion3: "Productividad",
            opcion4: "Rentabilidad",
        },
        respuesta: 3,
        categoria: "Cultura General",
        dificultad: "Fácil",
    },
    {
        preguntaTexto: "¿Qué científico alemán acorto el ciclo del nitrógeno?",
        preguntaImagen: "",
        tiempo: 15,
        opciones: {
            opcion1: "Fritz Haber",
            opcion2: "Hans Benz",
            opcion3: "Robert Lauterborn",
            opcion4: "Carl Troll",
        },
        respuesta: 1,
        categoria: "Cultura General",
        dificultad: "Media",
    },
    {
        preguntaTexto: "¿En qué año se crea la carrera de Ingeniería Industrial en México?",
        preguntaImagen: "",
        tiempo: 15,
        opciones: {
            opcion1: "1967",
            opcion2: "1883",
            opcion3: "1959",
            opcion4: "1838",
        },
        respuesta: 2,
        categoria: "Cultura General",
        dificultad: "Media",
    }
]