export let ronda1 = [
{
	preguntaTexto: "Etapa de la cadena de suministro que tiene lugar después de la entrega de mercancía al cliente final, y su objetivo es devolver el producto desde el cliente hasta el distribuidor o el proveedor.",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Logística de entrada",
		opcion2: "Logística de salida",
		opcion3: "Logística inversa",
		opcion4: "Logística de producción",
	},
	respuesta: 3,
	categoria: "Ingeniería en Logística",
	dificultad: "Media",
},
{
	preguntaTexto: "En este sistema el producto se fabrica con antelación. ",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "PULL",
		opcion2: "PUSH",
		opcion3: "STOCK",
		opcion4: "DEMANDA",
	},
	respuesta: 2,
	categoria: "Ingeniería en Logística",
	dificultad: "Media",
},
{
	preguntaTexto: "Calcula el  área del rectángulo más grande que puede inscribirse en un semicírculo de radio r",
	tiempo: 20,
	preguntaImagen: "",
	opciones: {
		opcion1: "r^2",
		opcion2: "2r^2",
		opcion3: "r^2 / 2",
		opcion4: "r^2 / pi",
	},
	respuesta: 1,
	categoria: "Matemáticas",
	dificultad: "Media",
},
{
	preguntaTexto: "Hace cinco años Amy tenía tres veces más edad que Mike. Si Mike tiene 10 años ahora ¿Qué edad tiene Amy?",
	tiempo: 30,
	preguntaImagen: "",
	opciones: {
		opcion1: "15",
		opcion2: "20",
		opcion3: "25",
		opcion4: "30",
	},
	respuesta: 2,
	categoria: "Matemáticas",
	dificultad: "Media",
},
{
	preguntaTexto: "El número 110100  binario corresponde a ",
	tiempo: 30,
	preguntaImagen: "",
	opciones: {
		opcion1: "100",
		opcion2: "63",
		opcion3: "52",
		opcion4: "24",
	},
	respuesta: 3,
	categoria: "Ingeniería en Datos",
	dificultad: "Media",
},
{
	preguntaTexto: "¿Cuál de los siguientes incisos NO es un lenguaje de programación?",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "LISA",
		opcion2: "BASIC",
		opcion3: "FORTRAN",
		opcion4: "COBOL",
	},
	respuesta: 1,
	categoria: "Ingeniería en Datos",
	dificultad: "Media",
},
{
	preguntaTexto: "Documento con el cual se finaliza la guerra entre los Estados Unidos Mexicanos y los Estados Unidos de América (1846-1848).",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Tratado de Versalles",
		opcion2: "Tratado de Guadalupe",
		opcion3: "Tratado de Córdoba",
		opcion4: "Tratado de Marruecos",
	},
	respuesta: 2,
	categoria: "Cultura General",
	dificultad: "Media",
},
{
	preguntaTexto: "Fecha en la cuál el equipo de futbol Cruz Azul rompió la maldición de 23 años sin ser campeón de la Liga MX",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "23 de mayo de 2020",
		opcion2: "06 de diciembre de 2019",
		opcion3: "30 de mayo de 2020",
		opcion4: "25 de mayo de 2021",
	},
	respuesta: 3,
	categoria: "Cultura General",
	dificultad: "Media",
},
{
	preguntaTexto: "¿Cuál es la propiedad de la materia que corresponde al recíproco de la densidad?",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Volumen específico",
		opcion2: "Densidad relativa",
		opcion3: "Peso",
		opcion4: "Gravedad específica",
	},
	respuesta: 1,
	categoria: "Ciencias básicas",
	dificultad: "Fácil",
},
{
	preguntaTexto: "Dos esferas pequeñas están separadas 10cm y tienen carga eléctrica de 100 y 20C. Si la carga eléctrica en cada una de ellas se duplica y la separación entre ellas también se duplica, la fuerza que cada una ejerce sobre la otra será...",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "La misma",
		opcion2: "El doble",
		opcion3: "La mitad",
		opcion4: "Cuatro veces menor",
	},
	respuesta: 1,
	categoria: "Ciencias básicas",
	dificultad: "Fácil",
},
{
	preguntaTexto: "Es el resultado de una trisomía en el par 18. Consiste en una serie de alteraciones más severas, las cuales implican generalmente la muerte en los primeros meses tras el nacimiento.",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Síndrome de Edwards",
		opcion2: "Síndrome de Patau",
		opcion3: "Síndrome de Turner",
		opcion4: "Síndrome de Klinefelter",
	},
	respuesta: 1,
	categoria: "Ingeniería Ambiental",
	dificultad: "Media",
},
{
	preguntaTexto: "Es la radiación emitida en forma continua por toda la materia cuya temperatura está por arriba del cero absoluto.",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Ultravioleta",
		opcion2: "Infrarroja",
		opcion3: "Gamma",
		opcion4: "Rayos X",
	},
	respuesta: 2,
	categoria: "Ingeniería Ambiental",
	dificultad: "Media",
},
{
	preguntaTexto: "Consegir metas y objetivos propuestos empleando los medios de la mejor forma posible (tiempo, insumos, dinero, esfuerzo, etc.). Esto responde a la definición de:",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Eficaz",
		opcion2: "Eficiente  ",
		opcion3: "Efervescente",
		opcion4: "Efectividad",
	},
	respuesta: 2,
	categoria: "Ingeniería industrial",
	dificultad: "Media",
},
{
	preguntaTexto: "Se reconoce que el 80% de las problemáticas corresponden all 20% causas comunes",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Diagrama de Ishikawa",
		opcion2: "Diagrama de Pareto",
		opcion3: "Diagrama de dispersión",
		opcion4: "Diagrama de flujo de problemas",
	},
	respuesta: 2,
	categoria: "Ingeniería industrial",
	dificultad: "Media",
},
{
	preguntaTexto: "Encuentra el volumen del sólido que se obtiene al girar la región acotada por y = x^3 , y = 8 , x = 0 alrededor del eje y",
	tiempo: 30,
	preguntaImagen: "",
	opciones: {
		opcion1: "96pi/5",
		opcion2: "48pi/3",
		opcion3: "72pi/7",
		opcion4: "45pi/2",
	},
	respuesta: 1,
	categoria: "Matemáticas",
	dificultad: "Difícil",
},
{
	preguntaTexto: "Si 10 pulgadas en un mapa representan una distancia actual de 100 pies, entonces ¿qué distancia real es representada por 25 pulgadas en el mapa?",
	tiempo: 30,
	preguntaImagen: "",
	opciones: {
		opcion1: "25 pies",
		opcion2: "100 pies",
		opcion3: "150 pies",
		opcion4: "250 pies",
	},
	respuesta: 4,
	categoria: "Matemáticas",
	dificultad: "Difícil",
},
{
	preguntaTexto: "Una mujer de 65kg desciende en un elevador que acelera brevemente a 0.20g hacia abajo. ¿cuál es el peso aparente de la mujer mientras desciende?",
	tiempo: 30,
	preguntaImagen: "",
	opciones: {
		opcion1: "512 N",
		opcion2: "52 kg",
		opcion3: "640 N",
		opcion4: "Pesa lo mismo, 65 kg.",
	},
	respuesta: 1,
	categoria: "Ciencias básicas",
	dificultad: "Difícil",
},
{
	preguntaTexto: "Una pelota es lanzada verticalmente hacia arriba, su trayectoria está dada por:  S = 30t - 16t^2 donde t es el tiempo en segundos y S es la altura sobre el piso. ¿En qué instante golpeará la pelota el piso?",
	tiempo: 30,
	preguntaImagen: "",
	opciones: {
		opcion1: "0 s",
		opcion2: "15/8 s",
		opcion3: "17/6 s",
		opcion4: "7/8 s",
	},
	respuesta: 2,
	categoria: "Ciencias básicas",
	dificultad: "Difícil",
},
{
	preguntaTexto: "¿Cuál es la tortuga de mayor tamaño?",
	tiempo: 10,
	preguntaImagen: "",
	opciones: {
		opcion1: "Tortuga gigante ",
		opcion2: "Tortuga japonesa ",
		opcion3: "Tortuga Kawama",
		opcion4: "Tortuga Laúd",
	},
	respuesta: 4,
	categoria: "Cultura General",
	dificultad: "Fácil",
},
{
	preguntaTexto: "¿Cuál es el nombre técnico del miedo o fobia a las alturas?",
	tiempo: 10,
	preguntaImagen: "",
	opciones: {
		opcion1: "Aracnofobia ",
		opcion2: "Tripofobia ",
		opcion3: "Acrofobia",
		opcion4: "Alturofobia",
	},
	respuesta: 3,
	categoria: "Cultura General",
	dificultad: "Fácil",
},
]