export let ronda3 = [
{
	preguntaTexto: "Hay n personas reunidas y todas se saludaron entre sí una sola vez. Si en total hubo 528 saludos, ¿cuánto vale n?",
	tiempo: 30,
	preguntaImagen: "",
	opciones: {
		opcion1: "33",
		opcion2: "32",
		opcion3: "34",
		opcion4: "35",
	},
	respuesta: 1,
	categoria: "Matemáticas",
	dificultad: "Difícil",
},
{
	preguntaTexto: "¿Cuántos números de tres dígitos, mayores a 330, se pueden formar con los números 0, 1, 2, 3, 4, 5 y 6 si cada dígito se puede usar una sola vez?",
	tiempo: 30,
	preguntaImagen: "",
	opciones: {
		opcion1: "105",
		opcion2: "115",
		opcion3: "100",
		opcion4: "95",
	},
	respuesta: 1,
	categoria: "Matemáticas",
	dificultad: "Difícil",
},
{
	preguntaTexto: "Pintó la Capilla Sixtina.",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Da Vinci",
		opcion2: "Miguel Angel",
		opcion3: "Botticelli",
		opcion4: "Tiziano",
	},
	respuesta: 2,
	categoria: "Cultura General",
	dificultad: "Fácil",
},
{
	preguntaTexto: '¿Quién es el autor de la frase "Es tan corto el amor, y es tan largo el olvido"?',
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Edgar Allan Poe",
		opcion2: "Gabriel García Márquez",
		opcion3: "Pablo Neruda",
		opcion4: "Miguel de Cervantes",
	},
	respuesta: 3,
	categoria: "Cultura General",
	dificultad: "Fácil",
},
{
	preguntaTexto: "Es una topología de red donde los nodos se conectan directamente con los otros",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Estrella",
		opcion2: "Malla",
		opcion3: "Bus",
		opcion4: "Serial",
	},
	respuesta: 2,
	categoria: "Ingeniería en Datos",
	dificultad: "Media",
},
{
	preguntaTexto: "El inventor de las tarjetas perforadas fue",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Herman Hollerith",
		opcion2: "Gottfried Leibnitz",
		opcion3: "Lady Lovelace",
		opcion4: "Joseph Jacquard",
	},
	respuesta: 1,
	categoria: "Ingeniería en Datos",
	dificultad: "Media",
},
{
	preguntaTexto: "¿Quién es el padre de la ingeniería industrial?",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: " Francisco Taylor",
		opcion2: "Francisco Monzalvo",
		opcion3: "Francisco N. Mateo ",
		opcion4: "Frederick Taylor",
	},
	respuesta: 4,
	categoria: "Ingeniería industrial",
	dificultad: "Media",
},
{
	preguntaTexto: "Significado de las siglas del ciclo PHVA",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Planear, hacer, visualizar, actuar",
		opcion2: "Planear, hacer, visualizar, analizar",
		opcion3: "Planear, hacer, verificar, actuar ",
		opcion4: "Planear, hacer, verificar, analizar",
	},
	respuesta: 4,
	categoria: "Ingeniería industrial",
	dificultad: "Media",
},
{
	preguntaTexto: "Ley que establece que un conductor que lleva una corriente eléctrica produce un campo magnético alrededor de él",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Oersted- Ampere",
		opcion2: "Coulomb",
		opcion3: "Gauss",
		opcion4: "Ohm",
	},
	respuesta: 1,
	categoria: "Ciencias básicas",
	dificultad: "Fácil",
},
{
	preguntaTexto: "¿Quién descubrió los rayos X?",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Nikola Tesla ",
		opcion2: "Isaac Newton",
		opcion3: "Thomas Edison",
		opcion4: "C. Roentgen",
	},
	respuesta: 4,
	categoria: "Ciencias básicas",
	dificultad: "Fácil",
},
{
	preguntaTexto: "El pirheliómetro mide",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Radiación reflejada",
		opcion2: "Radiación difusa",
		opcion3: "Radiación global",
		opcion4: "Radiación directa",
	},
	respuesta: 4,
	categoria: "Ingeniería Ambiental",
	dificultad: "Difícil",
},
{
	preguntaTexto: "Durante esta fase de la mitosis se produce una rotura de las conexiones entre las cromátidas hermanas que forman los cromosomas.",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Metafase",
		opcion2: "Prometafase",
		opcion3: "Telofase",
		opcion4: "Anafase",
	},
	respuesta: 4,
	categoria: "Ingeniería Ambiental",
	dificultad: "Difícil",
},
{
	preguntaTexto: "Determine la probabilidad  de que se extraiga un número primo de una urna que contiene pelotas númeradas del 1 al 20",
	tiempo: 30,
	preguntaImagen: "",
	opciones: {
		opcion1: "0,2",
		opcion2: "0,4",
		opcion3: "0,25",
		opcion4: "0,35",
	},
	respuesta: 2,
	categoria: "Matemáticas",
	dificultad: "Difícil",
},
{
	preguntaTexto: "Emma necesita ordenar fertilizante líquido para su compañía de jardinería. Ella piensa guardar el fertilizante en un tanque cilíndrico, pero no está segura cuanto fertilizante le cabe. El tanque mide 10 pies de altura y la base circular tiene un radio de 5 pies. ¿Cuál es volumen de este tanque de almacenamiento?",
	tiempo: 30,
	preguntaImagen: "",
	opciones: {
		opcion1: "1,570 ft^3",
		opcion2: "3,140  ft^3",
		opcion3: " 157 ft^3",
		opcion4: "785  ft^3",
	},
	respuesta: 4,
	categoria: "Matemáticas",
	dificultad: "Difícil",
},
{
	preguntaTexto: "¿Cuál fue el primer exoplaneta en ser descubierto?",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "51 Pegasi b",
		opcion2: "Andrómeda 1",
		opcion3: "Orión",
		opcion4: "Kepler-560b",
	},
	respuesta: 1,
	categoria: "Ciencias básicas",
	dificultad: "Difícil",
},
{
	preguntaTexto: "¿Cuál es la velocidad de rotación de la Tierra en el ecuador?",
	tiempo: 30,
	preguntaImagen: "",
	opciones: {
		opcion1: "4.3 km/h",
		opcion2: "1,150 km/h",
		opcion3: "1,670 km/h",
		opcion4: "2.7 km/h",
	},
	respuesta: 3,
	categoria: "Ciencias básicas",
	dificultad: "Difícil",
},
{
	preguntaTexto: "Enmarca las actividades necesarias para cumplir con el abastecimiento de sus productos. Se encarga de recibir las mercancías y de gestionar la información, evaluando los plazos y los costes de adquisición.",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Logística de salida",
		opcion2: "Logística integral",
		opcion3: "Logística inversa",
		opcion4: "Logística de entrada",
	},
	respuesta: 4,
	categoria: "Ingeniería en Logística",
	dificultad: "Media",
},
{
	preguntaTexto: "En este sistema se adapta la producción a la demanda efectiva, lo que significa que el producto se fabrica únicamente cuando se genera una compra.",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "PULL",
		opcion2: "PUSH",
		opcion3: "INVENTARIO",
		opcion4: "STOCK",
	},
	respuesta: 1,
	categoria: "Ingeniería en Logística",
	dificultad: "Media",
},
{
	preguntaTexto: "¿En qué país se celebra La Tomatina?",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Italia ",
		opcion2: "Francia ",
		opcion3: "España ",
		opcion4: "Rusia ",
	},
	respuesta: 3,
	categoria: "Cultura General",
	dificultad: "Media",
},
{
	preguntaTexto: "¿Qué colores tiene la bandera de Bosnia y Herzegovina?",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Azul, amarillo y blanco",
		opcion2: "Verde, rojo y morado",
		opcion3: "Amarillo, rojo y azul",
		opcion4: "Blanco, azul y rojo",
	},
	respuesta: 1,
	categoria: "Cultura General",
	dificultad: "Media",
},
{
	preguntaTexto: "Esta Norma Oficial Mexicana establece las características, el procedimiento de identificación, clasificación y los listados de los residuos peligrosos.",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "NOM-052-SEMARNAT-2005",
		opcion2: "NOM-098-SEMARNAT-2002",
		opcion3: "NOM-044-SEMARNAT-2006",
		opcion4: "NOM-083-SEMARNAT-2003",
	},
	respuesta: 1,
	categoria: "Ingeniería Ambiental",
	dificultad: "Media",
},
{
	preguntaTexto: "Termino que se le conoce al conjunto de tilacoides:",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Mitocontrias ",
		opcion2: "membrana plasmatica ",
		opcion3: "granums",
		opcion4: "cloroplasto",
	},
	respuesta: 3,
	categoria: "Ingeniería Ambiental",
	dificultad: "Media",
},
{
	preguntaTexto: "Proceso de acondicionar los productos para protegerlos, y/o agruparlos de manera temporal pensando en su manipulación, transporte y almacenamiento.",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Envase",
		opcion2: "Embalaje",
		opcion3: "Paletizado",
		opcion4: "Ninguna de las anteriores",
	},
	respuesta: 2,
	categoria: "Ingeniería en Logística",
	dificultad: "Media",
},
{
	preguntaTexto: "Es un sistema de gestión que permite integrar, controlar y gestionar todos los procesos empresariales. Es una herramienta de planificación y de optimización.",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "ERP (Enterprise Resource Planning)",
		opcion2: "CRM (Customer Relationship Management)",
		opcion3: "SCM (Supply Chain Management)",
		opcion4: "SRM (supplier relationship management)",
	},
	respuesta: 1,
	categoria: "Ingeniería en Logística",
	dificultad: "Media",
},
{
	preguntaTexto: "Reyansh está interesado en reservar un salón de fiesta para su hija en un centro de entretenimiento. Lo más que puede gastar son $275. El costo es $21 por niño y hay un cobro por reservación de $40. ¿Cuántos niños van a poder asistir a la fiesta?",
	tiempo: 30,
	preguntaImagen: "",
	opciones: {
		opcion1: "10",
		opcion2: "11",
		opcion3: "12",
		opcion4: "13",
	},
	respuesta: 2,
	categoria: "Matemáticas",
	dificultad: "Media",
},
{
	preguntaTexto: "44 es 80% ¿de qué número?",
	tiempo: 30,
	preguntaImagen: "",
	opciones: {
		opcion1: "51",
		opcion2: "53",
		opcion3: "55",
		opcion4: "57",
	},
	respuesta: 3,
	categoria: "Matemáticas",
	dificultad: "Media",
},
{
	preguntaTexto: "Es un medio de transmisión terrestre de alta velocidad",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Coaxial",
		opcion2: "Microondas",
		opcion3: "Satélite",
		opcion4: "Fibra óptica",
	},
	respuesta: 4,
	categoria: "Ingeniería en Datos",
	dificultad: "Media",
},
{
	preguntaTexto: "Es una topología de red donde los datos fluyen del emisor a un concentrador y este realiza todas las funciones de red",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Estrella",
		opcion2: "Malla",
		opcion3: "Bus",
		opcion4: "Serial",
	},
	respuesta: 1,
	categoria: "Ingeniería en Datos",
	dificultad: "Media",
},
{
	preguntaTexto: "Proceso de anotar, mediante líneas, cifras, signos y símbolos, las dimensiones de un objeto, sobre un dibujo o diseño.",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Acotar",
		opcion2: "Anotar",
		opcion3: "Delimitar",
		opcion4: "Apuntar",
	},
	respuesta: 1,
	categoria: "Ingeniería industrial",
	dificultad: "Media",
},
{
	preguntaTexto: "Se refiere al diseño de dispositivos a prueba de errores",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Producto milagro",
		opcion2: "Elemento de seguridad ",
		opcion3: "Poka-Yoke",
		opcion4: "Ninguno de los anteriores",
	},
	respuesta: 3,
	categoria: "Ingeniería industrial",
	dificultad: "Media",
},
{
	preguntaTexto: "¿Dónde se produce la adrenalina?",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Corazón",
		opcion2: "Pulmones",
		opcion3: "Glándulas Suprarrenales",
		opcion4: "Hígado",
	},
	respuesta: 3,
	categoria: "Ciencias básicas",
	dificultad: "Difícil",
},
{
	preguntaTexto: "¿Cuál es el elemento natural más denso que existe?",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Tantalio",
		opcion2: "Platino",
		opcion3: "Wolframio ",
		opcion4: "Osmio",
	},
	respuesta: 4,
	categoria: "Ciencias básicas",
	dificultad: "Difícil",
},
{
	preguntaTexto: "¿Cuál es el único mamífero capaz de volar?",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Murciélago ",
		opcion2: "Pato",
		opcion3: "Cacatúa",
		opcion4: "Ardilla voladora",
	},
	respuesta: 1,
	categoria: "Cultura General",
	dificultad: "Media",
},
{
	preguntaTexto: "Esposa de Ulises, en La Odisea.",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Penélope",
		opcion2: "Helena",
		opcion3: "Briseida",
		opcion4: "Circe",
	},
	respuesta: 1,
	categoria: "Cultura General",
	dificultad: "Media",
},
]