export let rondaextra2 = [
    {
        preguntaTexto: "Es la región de influencia que se encuetra alrededor de la carga, manefestada sobre otra carga cercana a el:",
        preguntaImagen: "",
        opciones: {
            opcion1: "intensidad de corriente",
            opcion2: "resistividad",
            opcion3: "diferencia de potencial",
            opcion4: "campo electrico",
        },
        respuesta: 4,
        categoria: "Ingeniería Ambiental",
        dificultad: "Difícil",
    },
    {
        preguntaTexto: "Cual de los siguientes elementos se encuentran en muy poca cantidad en los sistemas vivos",
        preguntaImagen: "",
        opciones: {
            opcion1: "fosforo",
            opcion2: "sodio",
            opcion3: "azufre",
            opcion4: "hidrogeno",
        },
        respuesta: 2,
        categoria: "Ingeniería Ambiental",
        dificultad: "Difícil",
    },
    {
        preguntaTexto: "Planeta del sistema solar más alejado del Sol.",
        preguntaImagen: "",
        opciones: {
            opcion1: "Mercurio",
            opcion2: "Saturno",
            opcion3: "Neptuno",
            opcion4: "Plutón",
        },
        respuesta: 3,
        categoria: "Cultura General",
        dificultad: "Fácil",
    },
    {
        preguntaTexto: "Consiste en la distribución, venta, compra, marketing y suministro de información de productos o servicios a través de Internet.",
        preguntaImagen: "",
        opciones: {
            opcion1: "IoT",
            opcion2: "E-commerce",
            opcion3: "Networking",
            opcion4: "Cadena de valor",
        },
        respuesta: 2,
        categoria: "Ingeniería en Logística",
        dificultad: "Media",
    },
    {
        preguntaTexto: "En 1924 trabajaba en Bell Telephone y desarrolló gráfica para controlar variables",
        preguntaImagen: "",
        opciones: {
            opcion1: "Dodge",
            opcion2: "Taguchi",
            opcion3: "Deming",
            opcion4: "Shewhart",
        },
        respuesta: 4,
        categoria: "Ingeniería en Datos",
        dificultad: "Media",
    },
    {
        preguntaTexto: "De los siguientes componentes. ¿cual se encuentra en mayor porcentaje en la atmosfera?",
        preguntaImagen: "",
        opciones: {
            opcion1: "carbono",
            opcion2: "dioxido de carbono",
            opcion3: "oxigeno",
            opcion4: "nitrogeno",
        },
        respuesta: 4,
        categoria: "Ingeniería Ambiental",
        dificultad: "Fácil",
    },
    {
        preguntaTexto: "¿Quién descubrió la inducción electromagnética?",
        preguntaImagen: "",
        opciones: {
            opcion1: "Thales de Mileto",
            opcion2: "Michael Faraday",
            opcion3: "Albert Einstein",
            opcion4: "Jordán Gauss",
        },
        respuesta: 2,
        categoria: "Ciencias básicas",
        dificultad: "Fácil",
    },
    {
        preguntaTexto: "¿Cuál es el resultado de 28 x 25?",
        preguntaImagen: "",
        opciones: {
            opcion1: "700",
            opcion2: "728",
            opcion3: "675",
            opcion4: "655",
        },
        respuesta: 1,
        categoria: "Matemáticas",
        dificultad: "Media",
    },
    {
        preguntaTexto: "En bases de datos, ¿Qué representan los rectángulos en el diagrama Entidad-Relación?",
        preguntaImagen: "",
        opciones: {
            opcion1: "La Cardinalidad",
            opcion2: "Las Relaciones",
            opcion3: "Los Atributos",
            opcion4: "Las Entidades",
        },
        respuesta: 4,
        categoria: "Ingeniería en Datos",
        dificultad: "Media",
    },
    {
        preguntaTexto: "Es la propiedad de la radiación de mayor valor en la piel humana",
        preguntaImagen: "",
        opciones: {
            opcion1: "Absortividad",
            opcion2: "Transmisividad",
            opcion3: "Emisividad",
            opcion4: "Permeabilidad",
        },
        respuesta: 3,
        categoria: "Ingeniería Ambiental",
        dificultad: "Fácil",
    },
    {
        preguntaTexto: "Se compone de todas las partes involucradas (eslabones), directa o indirectamente, para satisfacer la petición de un cliente.",
        preguntaImagen: "",
        opciones: {
            opcion1: "Cadena de suministro",
            opcion2: "Comercio",
            opcion3: "Satisfacción al cliente",
            opcion4: "Ninguna de las anteriores",
        },
        respuesta: 1,
        categoria: "Ingeniería en Logística",
        dificultad: "Media",
    },
    {
        preguntaTexto: "Estudia los procesos quimicos que tienen lugar en el medio ambiente o en alguna de sus partes como lo son: suelos, rios, lagos oceanos y la atmósfera",
        preguntaImagen: "",
        opciones: {
            opcion1: "quimica organica",
            opcion2: "quimica inorganica",
            opcion3: "quimica ambiental",
            opcion4: "quimica analitica",
        },
        respuesta: 3,
        categoria: "Ingeniería Ambiental",
        dificultad: "Difícil",
    },
    {
        preguntaTexto: "Cual de los siguientes elementos se encuentran en mayor abundancia en los sistemas vivos",
        preguntaImagen: "",
        opciones: {
            opcion1: "carbono, oxigeno, hidrogeno",
            opcion2: "arsenico, plomo, boro",
            opcion3: "fluor, kripton, berilio",
            opcion4: "potasio, cloro, yodo",
        },
        respuesta: 1,
        categoria: "Ingeniería Ambiental",
        dificultad: "Fácil",
    }
]