export let ronda2 = [
{
	preguntaTexto: 'Escritor conocido también como "El manco de Lepanto"',
	tiempo: 10,
	preguntaImagen: "",
	opciones: {
		opcion1: "Lope de Vega",
		opcion2: "Cervantes Saavedra",
		opcion3: "Quevedo",
		opcion4: "Shakespeare",
	},
	respuesta: 2,
	categoria: "Cultura General",
	dificultad: "Media",
},
{
	preguntaTexto: "¿Cuál es la capital de Nueva Zelanda?",
	tiempo: 10,
	preguntaImagen: "",
	opciones: {
		opcion1: "Auckland",
		opcion2: "Wellington",
		opcion3: "Hamilton",
		opcion4: "Rotorua",
	},
	respuesta: 1,
	categoria: "Cultura General",
	dificultad: "Media",
},
{
	preguntaTexto: "¿Cuál es la última capa de la atmósfera?",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Troposfera",
		opcion2: "Estratosfera ",
		opcion3: "Termosfera ",
		opcion4: "Exosfera",
	},
	respuesta: 4,
	categoria: "Ciencias básicas",
	dificultad: "Difícil",
},
{
	preguntaTexto: "¿Cuál es la temperatura promedio en la superficie solar?",
	tiempo: 30,
	preguntaImagen: "",
	opciones: {
		opcion1: "2,214°c",
		opcion2: "2,483°c",
		opcion3: "5,505°c",
		opcion4: "19,630°c",
	},
	respuesta: 3,
	categoria: "Ciencias básicas",
	dificultad: "Difícil",
},
{
	preguntaTexto: "Es el programa capaz de gestionar de forma sencilla, estructurada y ordenada, una o más BD.",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "SQL",
		opcion2: "LDD",
		opcion3: "LMD",
		opcion4: "SGBD",
	},
	respuesta: 4,
	categoria: "Ingeniería en Datos",
	dificultad: "Media",
},
{
	preguntaTexto: "Son redes de computadoras que abarcan una distancia de hasta 5 Km",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "MAN",
		opcion2: "LAN",
		opcion3: "WAN",
		opcion4: "Ninguno",
	},
	respuesta: 2,
	categoria: "Ingeniería en Datos",
	dificultad: "Media",
},
{
	preguntaTexto: "¿De cuántas formas diferentes se pueden ordenar las letras de la palabra PUEBLA?",
	tiempo: 30,
	preguntaImagen: "",
	opciones: {
		opcion1: "720",
		opcion2: "120",
		opcion3: "5040",
		opcion4: "640",
	},
	respuesta: 1,
	categoria: "Matemáticas",
	dificultad: "Difícil",
},
{
	preguntaTexto: "Sofía está manejando a Texas. Ella viaja a 70 kilómetros por hora por cada 2 horas, y a 63 kilómetros por hora cada 5 horas. En un período de 7 horas ¿Cuál es la velocidad promedio de Sofía?",
	tiempo: 30,
	preguntaImagen: "",
	opciones: {
		opcion1: "64 km/h",
		opcion2: "65 km/h",
		opcion3: "66 km/h",
		opcion4: "67 km/h",
	},
	respuesta: 2,
	categoria: "Matemáticas",
	dificultad: "Difícil",
},
{
	preguntaTexto: "Componente que almacena energía en forma de campo eléctrico",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Resistor",
		opcion2: "Inductor",
		opcion3: "Condensador",
		opcion4: "Diodo rectificador",
	},
	respuesta: 3,
	categoria: "Ciencias básicas",
	dificultad: "Fácil",
},
{
	preguntaTexto: "¿Qué sucede si el flujo a través de un circuito eléctrico varía con el tiempo?",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Se observa un campo",
		opcion2: "Existe una variación de flujo",
		opcion3: "Sobresale una constante rígida",
		opcion4: "Se puede observar una corriente en el circuito",
	},
	respuesta: 4,
	categoria: "Ciencias básicas",
	dificultad: "Fácil",
},
{
	preguntaTexto: "¿Quién es conocido como el padre de la estrategia?(Matriz de las 5 fuerzas)",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Johannes Kepler",
		opcion2: "Alfred Chandler",
		opcion3: "Christensen Clayton",
		opcion4: "Michael Porter",
	},
	respuesta: 4,
	categoria: "Ingeniería en Logística",
	dificultad: "Media",
},
{
	preguntaTexto: "Es una predicción de lo que ocurrirá en el futuro. Forman la base de toda la planeación de la cadena de suministro",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Oferta",
		opcion2: "Estimación",
		opcion3: "Prónostico",
		opcion4: "Ninguna de las anteriores",
	},
	respuesta: 3,
	categoria: "Ingeniería en Logística",
	dificultad: "Media",
},
{
	preguntaTexto: "Según el principio de cautela",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "No se puede realizar una actividad que está demostrado que produce un impacto ambiental inaceptable.",
		opcion2: "No se puede realizar una actividad potencialmente peligrosa hasta que no se demuestre que no hay ningún peligro",
		opcion3: "No se evaluarán sitios potencialmente peligrosos.",
		opcion4: "Hay que tener mucho cuidado al evaluar los impactos ambientales.",
	},
	respuesta: 2,
	categoria: "Ingeniería Ambiental",
	dificultad: "Media",
},
{
	preguntaTexto: "Este tipo de suelo cuenta con partículas muy finas que forman barro cuando están saturadas de agua",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Arcilloso",
		opcion2: "Limoso",
		opcion3: "Arenoso",
		opcion4: "Calizo",
	},
	respuesta: 1,
	categoria: "Ingeniería Ambiental",
	dificultad: "Media",
},
{
	preguntaTexto: "Alberto, Benjamín y Carlota hicieron un total de 20 sándwiches.Benjamín hizo 3 veces más que Alberto, y Carlota hizo el doble que Benjamín. ¿Cuántos sándwiches hizo Alberto?",
	tiempo: 30,
	preguntaImagen: "",
	opciones: {
		opcion1: "4",
		opcion2: "6",
		opcion3: "2",
		opcion4: "10",
	},
	respuesta: 3,
	categoria: "Matemáticas",
	dificultad: "Media",
},
{
	preguntaTexto: "Es la ciencia deductiva que se dedica al estudio de las propiedades de los entes abstractos y de sus relaciones:",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Matemáticas",
		opcion2: "Algebra",
		opcion3: "Geometria",
		opcion4: "Estadistica",
	},
	respuesta: 2,
	categoria: "Matemáticas",
	dificultad: "Media",
},
{
	preguntaTexto: "Nivel Sigma que permite 3.4 defectos por cada millón de oportunidades ",
	tiempo: 20,
	preguntaImagen: "",
	opciones: {
		opcion1: "3",
		opcion2: "4",
		opcion3: "5",
		opcion4: "6",
	},
	respuesta: 4,
	categoria: "Ingeniería industrial",
	dificultad: "Media",
},
{
	preguntaTexto: "Los siguientes diagramas son sinónimos excepto uno, ¿Cual es el impostor?",
	tiempo: 15,
	preguntaImagen: "",
	opciones: {
		opcion1: "Diagrama de Ishikawa",
		opcion2: "Diagrama de cola de pescado",
		opcion3: "Diagrama de causa-efecto",
		opcion4: "Diagrama de flujo",
	},
	respuesta: 4,
	categoria: "Ingeniería industrial",
	dificultad: "Media",
},
{
	preguntaTexto: "Año en que teminó la Segunda Guerra Mundial",
	tiempo: 10,
	preguntaImagen: "",
	opciones: {
		opcion1: "1939",
		opcion2: "1943",
		opcion3: "1945",
		opcion4: "1944",
	},
	respuesta: 3,
	categoria: "Cultura General",
	dificultad: "Fácil",
},
{
	preguntaTexto: '¿Quién es el protagonista de la saga de videojuegos de "The Legnd of Zelda?',
	tiempo: 10,
	preguntaImagen: "",
	opciones: {
		opcion1: "Zelda",
		opcion2: "Link",
		opcion3: "Saria ",
		opcion4: "Navi",
	},
	respuesta: 2,
	categoria: "Cultura General",
	dificultad: "Fácil",
},
]